apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: soccer-blog
  name: soccer-blog
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5002
  selector:
    app: soccer-blog
status:
  loadBalancer: {}
